version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    # Uncomment / adjust the following if you want Dependabot to apply specific labels or reviewers
    # labels:
    #   - "dependencies"
    # reviewers:
    #   - "your-github-username"
